/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.heretic.discovery;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        EurekaServerApplication classUnderTest = new EurekaServerApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
